name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit  
  build:
    uses: ./.github/workflows/docker.yml
    secrets: inherit
  